name: Node.js CI

on:
  push:
    branches:
      - main  # ejecuta pruebas automaticas al hacer un push
 
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Especifica la versión de Node.js que estás utilizando

      - name: Install dependencies
        run: npm install  # Instala las dependencias 

      - name: Run tests
        run: npm test  # Ejecuta tus pruebas usando npm
